ALTER TABLE "Scans" ADD COLUMN "fileName" varchar(255);

ALTER TABLE "Scans" ALTER COLUMN width DROP NOT NULL;
ALTER TABLE "Scans" ALTER COLUMN height DROP NOT NULL;
ALTER TABLE "Scans" ALTER COLUMN "zoomLevel" DROP NOT NULL;